#!/bin/bash

# Use ClamAV to do a virus scan of the repo. Only display files where a virus is found

# Colors
# shellcheck disable=SC1117
end="\033[0m"
red="\033[0;31m"
green="\033[0;32m"

function red {
  echo -e "${red}${1}${end}"
}

function green {
  echo -e "${green}${1}${end}"
}

green "#### Starting Virus Scan ####"

clamd & 
CLAMD_PID=$!

SOCKET=/var/run/clamav/clamd.ctl
WAITED=0

# wait for unix socket with a max timeout of 60s
until [ -S "${SOCKET}" ] || [ "${WAITED}" -ge 60 ]; do
  sleep 1
  WAITED=$((WAITED + 1))
done

if [ ! -s "${SOCKET}" ]; then
  red "ERROR: clamd did not start within 60 seconds. Aborting scan."
  kill "${CLAMD_PID}" 2>/dev/null
  exit 1
fi

clamdscan \
  --multiscan \
  --fdpass \
  --exclude='./.composer-cache' \
  --exclude='./node_modules_cache' \
  -ri .

SCAN_EXIT=$?

if [ $SCAN_EXIT -eq 0 ]
then
  green "Clean: no viruses found"
  echo ""
  kill "${CLAMD_PID}"
  wait "${CLAMD_PID}" 2>/dev/null
  exit "${SCAN_EXIT}"
elif [ $SCAN_EXIT -eq 1 ]
then
  red "**** INFECTED FILE FOUND!!! **** PLEASE SEE REPORT ABOVE ****"
  echo ""
  exit 1
  kill "${CLAMD_PID}"
  wait "${CLAMD_PID}" 2>/dev/null
  exit "${SCAN_EXIT}"

else
  red "Virus scanner internal error."
  echo ""
  kill "${CLAMD_PID}"
  wait "${CLAMD_PID}" 2>/dev/null

  exit 0
fi

# Ensure scan is closed
kill "${CLAMD_PID}"
wait "${CLAMD_PID}" 2>/dev/null

